In [14]:
# Enter key-value pairs separated by spaces
data = {key: value for key, value in input("Enter key-value pairs separated by spaces: ").split()}

In [15]:
# defaultdict explanation it takes the default value of the dict to the key when not given a value
from collections import defaultdict
d  = defaultdict(list)
d['python'].append("awsome")
d['something else'].append("not relevent")
d['python'].append("language")
for i in d.items():
    print(i) 

TypeError: first argument must be callable or None

In [16]:
# example 1 for namedtuple
from collections import namedtuple
point = namedtuple('point', 'x,y')
pt1 = point(1,2)
pt2 = point(4,5)
dot_product = (pt1.x * pt2.x) + (pt1.y * pt2.y)
print(dot_product)

14


In [17]:
# example 2 for a nametuple
from collections import namedtuple
Car = namedtuple('Car', 'Price, Mileage, Color, Class')
xyz = Car(Price = '200000', Mileage = '18', Color = 'red', Class = 'Y')

print(xyz)
print(xyz.Color)


Car(Price='200000', Mileage='18', Color='red', Class='Y')
red


In [18]:
from collections import OrderedDict
# it preserves the order in which items are added when iteratin through the dictionary
dict = OrderedDict()

dict['apple'] = 3
dict['banana'] = 2
dict['cherry'] = 4

for key, value in dict.items():
    print(key, value)

apple 3
banana 2
cherry 4


In [19]:
from itertools import permutations
print (permutations(['1','2','3','4']))


In [20]:
print(list(permutations(['1','2','3','4'])))

TypeError: 'list' object is not callable

In [21]:
print(list(permutations(['1','2','3'],2)))

TypeError: 'list' object is not callable

In [22]:
print(list(permutations('abc', 2)))

TypeError: 'list' object is not callable

In [23]:
from itertools import combinations
print(list(combinations('12345', 2)))

TypeError: 'list' object is not callable

In [12]:
from itertools import combinations
A = [1,4,2,3,5,6]
my = list(combinations(A, 4))

TypeError: 'list' object is not callable

In [26]:
from collections import Counter
# counter stores the elements in dictionary keys and their count in dictionary values
myList = [1,1,2,3,4,5,3,2,3,4,2,1,2,3]
print(Counter(myList))

Counter({2: 4, 3: 4, 1: 3, 4: 2, 5: 1})


In [27]:
print(Counter(myList).items())

dict_items([(1, 3), (2, 4), (3, 4), (4, 2), (5, 1)])


In [29]:
print(Counter(myList).keys())

dict_keys([1, 2, 3, 4, 5])


In [30]:
print(Counter(myList).values())

dict_values([3, 4, 4, 2, 1])


In [2]:
from collections import deque
d = deque()
d.append(1)
print(d)


deque([1])


In [4]:
d.appendleft(2)
print(d)

deque([2, 2, 1])


In [5]:
d.clear()
print(d)

deque([])


In [6]:
d.extend('1')
print(d)

deque(['1'])


In [7]:
d.extendleft('234')
print(d)

deque(['4', '3', '2', '1'])


In [8]:
d.count('1')

1

In [9]:
d.pop()

'1'

In [10]:
print(d)

deque(['4', '3', '2'])


In [11]:
d.popleft()
print(d)

deque(['3', '2'])


In [12]:
d.remove('2')

In [13]:
print(d)

deque(['3'])


In [16]:
d = deque(['3','2','7','8','9','6'])
print(d)

deque(['3', '2', '7', '8', '9', '6'])


In [17]:
d.remove('7')
print(d)

deque(['3', '2', '8', '9', '6'])


In [19]:
d.reverse()

In [20]:
print(d)

deque(['6', '9', '8', '2', '3'])


In [21]:
d.rotate(4)

In [22]:
print(d)

deque(['9', '8', '2', '3', '6'])


In [1]:
def check_palindrome(string):
    
    # base case
    if string == "":
        return ""

    # small work to be done
    first_char = string[0]
    remaining_reversed_string = string[1:]

    result = rev_string(remaining_reversed_string) + first_char
    if result == string:
        return True 
    else:
        return False 

In [2]:
def is_palindrome(word):
    if len(word) == 1:
        return word
    check = is_palindrome(word[1:]) + word[0]
    if check == word:
        return "string is Palindrome"
    else:
        return "string is not Palindrome"


In [4]:
is_palindrome("civic")

'string is not Palindrome'

In [2]:
import calendar
print(calendar.TextCalendar(firstweekday=6).formatyear(2023))

                                  2023

      January                   February                   March
Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7                1  2  3  4                1  2  3  4
 8  9 10 11 12 13 14       5  6  7  8  9 10 11       5  6  7  8  9 10 11
15 16 17 18 19 20 21      12 13 14 15 16 17 18      12 13 14 15 16 17 18
22 23 24 25 26 27 28      19 20 21 22 23 24 25      19 20 21 22 23 24 25
29 30 31                  26 27 28                  26 27 28 29 30 31

       April                      May                       June
Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa
                   1          1  2  3  4  5  6                   1  2  3
 2  3  4  5  6  7  8       7  8  9 10 11 12 13       4  5  6  7  8  9 10
 9 10 11 12 13 14 15      14 15 16 17 18 19 20      11 12 13 14 15 16 17
16 17 18 19 20 21 22      21 22 23 24 25 26 27      18 19 20 21 22 23 24
23 24 25 26 27 28 29      28 

In [6]:
# to find the absolute value of a comlex number
import cmath
z = complex(-1.0, 0.0)
print(cmath.phase(z))

3.141592653589793


In [7]:
print(divmod(177,10))

(17, 7)


In [9]:
import numpy

arr1 = numpy.array([1,2,3])
arr2 = numpy.array([4,5,6])
arr3 = numpy.array([7,8,9])

print(numpy.concatenate((arr1, arr2, arr3)))

[1 2 3 4 5 6 7 8 9]


In [12]:
import numpy 
print(numpy.zeros((1,2), dtype = int))

[[0 0]]


In [13]:
import numpy 
print(numpy.ones((4,5), dtype = int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
import numpy
print(numpy.identity(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [18]:
print(numpy.eye(8, 7, k=-2))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


In [23]:
import numpy as np
arr1 = numpy.array([1.1, 1.2, 4.4, 3.3, 7.7, 7.8, 6.7])

print(numpy.floor(arr1)) # for the floor before integer basically
print(numpy.ceil(arr1)) # for the ceiling after integer basically
print(numpy.rint(arr1)) # for the nearest rounded integer

[1. 1. 4. 3. 7. 7. 6.]
[2. 2. 5. 4. 8. 8. 7.]
[1. 1. 4. 3. 8. 8. 7.]


In [24]:
import numpy as np

arr1 = np.array([ [1,2], [3,4] ])
print(arr1)

[[1 2]
 [3 4]]


In [26]:
print(np.mean(arr1, axis = 0)) # axis means it calculates the mean for each column

[2. 3.]


In [27]:
print(np.mean(arr1, axis = 1)) # axis means it calculates the mean for each column

[1.5 3.5]


In [29]:
print(np.var(arr1, axis = 1)) 

[0.25 0.25]


In [31]:
print(np.std(arr1, axis = 1)) 

[0.5 0.5]


In [33]:
import numpy as np

A = numpy.array([1,2])
B = numpy.array([3,4])

print(numpy.dot(A, B))
print(numpy.cross(A, B))

11
-2


In [2]:
# Example lists
names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 22]
grades = ["A", "B", "C"]

# # Using zip with three iterables
# combined_data = zip(names, ages, grades)

# # Converting the result to a list for visualization
# combined_list = list(combined_data)

# Displaying the combined list
print(list(zip(names, ages, grades)))


[('Alice', 25, 'A'), ('Bob', 30, 'B'), ('Charlie', 22, 'C')]


In [3]:
rows = 5

for i in range(1, rows + 1):
    print(" " * (rows - i) + "*" * i)


    *
   **
  ***
 ****
*****


In [1]:
rows = 5

for i in range(1, rows + 1):
    if i == 1 or i == rows:
        print(" " * (rows - i) + "*" * (2 * i - 1))
    else:
        print(" " * (rows - i) + "*" + " " * (2 * i - 3) + "*")

    *
   * *
  *   *
 *     *
*********


In [6]:
class greet:
    def greet(self, name):
        print("good day: "+name)

greet1 = greet()

greet1.greet("kartik")

good day: kartik
